# This is a basic workflow to help you get started with Actions

name: TradeMate CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_DEV_HOST }}
        username: ${{ secrets.DEPLOY_DEV_USERNAME }}
        key: ${{ secrets.DEPLOY_DEV_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/sandbox.trademate.one
          git reset --hard
          git pull origin dev
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh  
          git status
          composer install
          php artisan optimize:clear
          npm install
          npm run build          